name: git_hub_tracker
description: My Flutter Project for Exams
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.0

  email_validator: ^2.1.17
  cached_network_image: ^3.2.3
  simple_chips_input: ^1.0.0

  github: ^9.17.0

  oauth2: ^2.0.2
  flutter_secure_storage: ^9.0.0

  dio: ^5.3.3
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^3.0.0-dev.0
  freezed_annotation: ^2.4.1

  #maybe to delete
  dartz: ^0.10.1
  webview_flutter: ^4.4.2
  flash: ^3.0.5+2



dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.1
  freezed: ^2.4.5

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/profile.jpg
    - assets/images/actor_placeholder.jpg
    - assets/images/title.png
    - assets/images/UserProfile.png


  uses-material-design: true
